# Generated by Django 5.1.6 on 2025-03-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vehicle_alter_user_email_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semiAutomatic', 'Semi Automatic')], max_length=30, null=True),
        ),
    ]
