# Generated by Django 5.1.6 on 2025-03-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vehicle_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='kilometers',
            field=models.IntegerField(null=True),
        ),
    ]
