# Generated by Django 5.1.6 on 2025-03-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_appointment_cancellation_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cancellation_reason',
        ),
    ]
