# Generated by Django 5.1.7 on 2025-03-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_chat_receiver_alter_chat_sender_cancellation'),
        ('myapp', '0009_cancellation'),
    ]

    operations = [
    ]
