# Generated by Django 5.1.7 on 2025-03-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_purchase_appointment_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
