# Generated by Django 5.1.7 on 2025-03-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
